# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 14:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.TextField(max_length=255)),
                ('maskFilename', models.TextField(max_length=255)),
                ('byHandObtained', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateOfConclusion', models.DateField()),
                ('doctorsName', models.TextField(max_length=255)),
                ('comment', models.TextField(max_length=2047)),
            ],
        ),
        migrations.CreateModel(
            name='DicomImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.TextField(max_length=255)),
                ('acquisition_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TrainableModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('structureFilename', models.TextField(max_length=255)),
                ('weightsFilename', models.TextField(max_length=255)),
                ('creationDate', models.DateField()),
                ('description', models.TextField(max_length=2047)),
            ],
        ),
        migrations.CreateModel(
            name='OrganContour',
            fields=[
                ('contour_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='viewer.Contour')),
                ('organ', models.TextField(max_length=255)),
            ],
            bases=('viewer.contour',),
        ),
        migrations.CreateModel(
            name='PathologyContour',
            fields=[
                ('contour_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='viewer.Contour')),
            ],
            bases=('viewer.contour',),
        ),
        migrations.AddField(
            model_name='dicomimage',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='viewer.Institution'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='disease',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='viewer.Disease'),
        ),
        migrations.AddField(
            model_name='contour',
            name='producedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='viewer.TrainableModel'),
        ),
        migrations.AddField(
            model_name='pathologycontour',
            name='diagnosis',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='viewer.Diagnosis'),
        ),
    ]
