# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 15:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='institution',
            old_name='name',
            new_name='title',
        ),
    ]
