# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 22:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('viewer', '0002_auto_20160828_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='dicomimage',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dicom_images', to=settings.AUTH_USER_MODEL),
        ),
    ]
