# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 20:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0003_dicomimage_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dicomimage',
            name='filename',
        ),
        migrations.AddField(
            model_name='dicomimage',
            name='file',
            field=models.FileField(default='data/dicom_images/default.dcm', upload_to='data/dicom_images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dicomimage',
            name='owner',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='dicom_images', to=settings.AUTH_USER_MODEL),
        ),
    ]
