# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-07 12:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0005_auto_20160907_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='contour',
            name='dicomImage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='viewer.DicomImage'),
        ),
    ]
