# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-10 06:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0006_contour_dicomimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dicomimage',
            old_name='acquisition_date',
            new_name='acquisitionDate',
        ),
    ]
