# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-22 20:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('viewer', '0008_auto_20160910_1015'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='viewer.Institution')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='contour',
            name='contourFile',
            field=models.FileField(default='viewer/data/contour_files/default.npz', upload_to='viewer/data/contour_files/'),
        ),
        migrations.AlterField(
            model_name='contour',
            name='maskFile',
            field=models.FileField(default='viewer/data/mask_files/default.npz', upload_to='viewer/data/mask_files/'),
        ),
        migrations.AlterField(
            model_name='dicomimage',
            name='file',
            field=models.FileField(default='viewer/data/dicom_images/default.dcm', upload_to='viewer/data/dicom_images/'),
        ),
        migrations.AlterField(
            model_name='trainablemodel',
            name='structureFile',
            field=models.FileField(default='viewer/data/trainable_models/structures/default.yaml', upload_to='viewer/data/trainable_models/structures/'),
        ),
        migrations.AlterField(
            model_name='trainablemodel',
            name='weightsFile',
            field=models.FileField(default='viewer/data/trainable_models/weights/default.h5', upload_to='viewer/data/trainable_models/weights'),
        ),
    ]
